# Generated by Django 5.1 on 2026-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_umur', models.IntegerField()),
                ('max_umur', models.IntegerField()),
                ('max_tenor', models.IntegerField()),
                ('allowed_job', models.CharField(max_length=100)),
            ],
        ),
    ]
