# Generated by Django 5.1 on 2026-04-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='allowed_job',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='max_tenor',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='max_umur',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='min_umur',
        ),
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.product')),
            ],
        ),
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.rule')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.rulecategory'),
        ),
    ]
