# Generated by Django 5.1 on 2026-04-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bankrule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.product'),
        ),
    ]
