# Generated by Django 5.1 on 2026-04-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bankrule_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='key',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='bankrule',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankrule',
            name='product',
        ),

        # ✅ FIX: kasih default ID (contoh: 1)
        migrations.AddField(
            model_name='bankrule',
            name='bank_product',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rules',
                to='banks.bankproduct'
            ),
            preserve_default=False,
        ),

        # ✅ FIX: default string
        migrations.AddField(
            model_name='rule',
            name='operator',
            field=models.CharField(
                choices=[
                    ('equals', 'Equals'),
                    ('not_equals', 'Not Equals'),
                    ('gt', 'Greater Than'),
                    ('lt', 'Less Than'),
                    ('contains', 'Contains')
                ],
                default='equals',
                max_length=20
            ),
            preserve_default=False,
        ),

        # ✅ FIX: default string kosong
        migrations.AddField(
            model_name='rule',
            name='value',
            field=models.CharField(
                default='',
                max_length=100
            ),
            preserve_default=False,
        ),

        # ✅ FIX: description string kosong
        migrations.AlterField(
            model_name='bankrule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
