# Generated by Django 5.1 on 2026-04-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_rename_key_rule_field_remove_bankrule_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrule',
            name='bank_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bankproduct'),
        ),
    ]
