# Generated by Django 5.1 on 2026-04-09 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_alter_bankrule_bank_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='field',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='bankrule',
            name='bank_product',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='value',
        ),
        migrations.AddField(
            model_name='bankrule',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.product'),
        ),
        migrations.AlterField(
            model_name='bankrule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
