# Generated by Django 5.1 on 2026-04-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_rename_field_rule_key_remove_bankrule_bank_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
