# Generated by Django 5.1 on 2026-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_bankproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='max_plafond',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='max_tenor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='min_plafond',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='min_tenor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
