# Generated by Django 5.1 on 2026-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_bankproduct_max_plafond_bankproduct_max_tenor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='max_age_end',
            field=models.IntegerField(blank=True, help_text='Maksimal usia saat kredit lunas (umur + tenor)', null=True),
        ),
    ]
