# Generated by Django 5.1 on 2026-04-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_bankproduct_max_age_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_pks',
            field=models.BooleanField(default=False),
        ),
    ]
