# Generated by Django 5.1 on 2026-04-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_bank_is_pks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='min_lama_usaha',
            field=models.IntegerField(blank=True, help_text='Minimal lama usaha (dalam tahun)', null=True),
        ),
    ]
