# Generated by Django 5.1 on 2026-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('umur', models.IntegerField()),
                ('jenis_pinjaman', models.CharField(choices=[('KPR', 'KPR'), ('MULTIGUNA', 'Multiguna'), ('MODAL_KERJA', 'Modal Kerja')], max_length=20)),
                ('jumlah_pinjaman', models.IntegerField()),
                ('tenor', models.IntegerField()),
                ('pekerjaan', models.CharField(choices=[('KARYAWAN', 'Karyawan'), ('WIRASWASTA', 'Wiraswasta'), ('PROFESIONAL', 'Profesional')], max_length=20)),
                ('status_pekerjaan', models.CharField(choices=[('TETAP', 'Tetap'), ('KONTRAK', 'Kontrak')], max_length=20)),
                ('bentuk_perusahaan', models.CharField(blank=True, choices=[('PT', 'PT'), ('CV', 'CV'), ('PERORANGAN', 'Perorangan')], max_length=20, null=True)),
                ('bidang_usaha', models.CharField(blank=True, choices=[('FNB', 'F&B'), ('RETAIL', 'Retail'), ('JASA', 'Jasa')], max_length=20, null=True)),
                ('jaminan', models.CharField(choices=[('RUMAH', 'Rumah'), ('RUKO', 'Ruko'), ('TANAH', 'Tanah')], max_length=20)),
                ('jenis_sertifikat', models.CharField(choices=[('SHM', 'SHM'), ('HGB', 'HGB')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
