# Generated by Django 5.1 on 2026-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bentuk_perusahaan',
            field=models.CharField(blank=True, choices=[('PERORANGAN', 'Perorangan'), ('PT', 'PT'), ('CV', 'CV'), ('YAYASAN', 'Yayasan'), ('PEMERINTAH', 'Institusi Pemerintahan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bidang_usaha',
            field=models.CharField(blank=True, choices=[('PERTANIAN', 'Pertanian, Kehutanan dan Perikanan'), ('PERTAMBANGAN', 'Pertambangan dan Penggalian'), ('INDUSTRI', 'Industri Pengolahan'), ('LISTRIK_GAS', 'Pengadaan Listrik, Gas, Uap'), ('AIR_LIMBAH', 'Pengelolaan Air & Limbah'), ('KONSTRUKSI', 'Konstruksi'), ('PERDAGANGAN', 'Perdagangan & Reparasi'), ('AKOMODASI', 'Akomodasi & Makan Minum'), ('INFORMASI', 'Informasi dan Komunikasi'), ('KEUANGAN', 'Keuangan dan Asuransi'), ('REAL_ESTATE', 'Real Estat'), ('PROFESIONAL', 'Aktivitas Profesional'), ('SEWA', 'Sewa & Agen Usaha'), ('PEMERINTAH', 'Administrasi Pemerintahan'), ('PENDIDIKAN', 'Pendidikan'), ('KESEHATAN', 'Kesehatan dan Sosial'), ('HIBURAN', 'Kesenian & Hiburan'), ('JASA', 'Jasa Lainnya'), ('RUMAH_TANGGA', 'Aktivitas Rumah Tangga'), ('INTERNASIONAL', 'Badan Internasional')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='jaminan',
            field=models.CharField(choices=[('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko'), ('RUKAN', 'Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('INVOICE', 'Invoice'), ('SPK_PO', 'SPK/PO'), ('BPKB', 'BPKB Mobil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_kelamin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('KMG', 'Kredit Multiguna'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('REF_MOBIL', 'Refinancing Mobil/Motor'), ('REF_MESIN', 'Refinancing Mesin'), ('REF_ALAT_BERAT', 'Refinancing Alat Berat'), ('HOME_REF', 'Home Refinancing'), ('KTA', 'Kredit Tanpa Agunan'), ('KRK_PERORANGAN', 'KRK Perorangan'), ('MODAL_KERJA', 'Kredit Modal Kerja'), ('REKENING_KORAN', 'Rekening Koran'), ('KTA_SELLER', 'KTA Online Seller'), ('INVESTASI_INDIVIDU', 'Kredit Investasi Individu'), ('INVOICE_FINANCING', 'Invoice Financing'), ('DEPOSITO', 'Deposito Berjangka'), ('TAKE_OVER', 'Take Over'), ('BRIDGING', 'Bridging Loan'), ('KPA_PERUSAHAAN', 'KPA Perusahaan'), ('INVESTASI_PERUSAHAAN', 'Kredit Investasi Perusahaan'), ('KRK_PERUSAHAAN', 'KRK Perusahaan'), ('MODAL_PERUSAHAAN', 'Kredit Modal Perusahaan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_sertifikat',
            field=models.CharField(choices=[('SHM', 'Sertifikat Hak Milik'), ('HGB', 'Sertifikat Hak Guna Bangunan'), ('SHRS', 'Sertifikat Hak Satuan Rumah Susun'), ('AJB', 'Akta Jual Beli'), ('GIRIK', 'Surat Girik')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='pekerjaan',
            field=models.CharField(choices=[('KARYAWAN', 'Karyawan'), ('WIRASWASTA', 'Wiraswasta'), ('PROFESIONAL', 'Profesional'), ('ASN', 'Pegawai Pemerintah (ASN/PSN)'), ('TNI_POLRI', 'TNI/POLRI'), ('LAWYER', 'Lawyer'), ('PERUSAHAAN', 'Perusahaan')], max_length=50),
        ),
    ]
