# Generated by Django 5.1 on 2026-04-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_bentuk_perusahaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
    ]
