# Generated by Django 5.1 on 2026-04-08 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jenis_pengajuan',
            field=models.CharField(choices=[('BARU', 'Baru'), ('TAKEOVER', 'Take Over')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='join_income',
            field=models.CharField(blank=True, choices=[('TIDAK', 'Tidak'), ('PASANGAN', 'Pasangan'), ('ORANG_TUA', 'Orang Tua')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lama_kerja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='restruktur',
            field=models.CharField(choices=[('TIDAK', 'Tidak'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='status_slik',
            field=models.CharField(choices=[('KOL1', 'Kol 1'), ('KOL2', 'Kol 2'), ('KOL3', 'Kol 3'), ('KOL5', 'Kol 5')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sumber_penghasilan',
            field=models.CharField(choices=[('GAJI_TRANSFER', 'Gaji Transfer'), ('GAJI_TUNAI', 'Gaji Tunai'), ('CAMPURAN', 'Campuran')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='bentuk_perusahaan',
            field=models.CharField(blank=True, choices=[('PERORANGAN', 'Perorangan'), ('PT', 'PT'), ('CV', 'CV'), ('YAYASAN', 'Yayasan'), ('PEMERINTAH', 'Pemerintah')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='jaminan',
            field=models.CharField(choices=[('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER', 'Take Over'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Kredit Rekening Koran'), ('INVOICE', 'Invoice Financing'), ('SPK', 'SPK / PO Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('BRIDGING', 'Bridging Loan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_sertifikat',
            field=models.CharField(choices=[('SHM', 'SHM'), ('HGB', 'HGB'), ('SHRS', 'SHRS'), ('AJB', 'AJB'), ('GIRIK', 'Girik')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='pekerjaan',
            field=models.CharField(choices=[('KARYAWAN', 'Karyawan'), ('WIRASWASTA', 'Wiraswasta'), ('PROFESIONAL', 'Profesional'), ('ASN', 'ASN / Pemerintah'), ('TNI_POLRI', 'TNI / POLRI'), ('LAWYER', 'Lawyer'), ('BADAN_USAHA', 'Badan Usaha')], max_length=50),
        ),
    ]
