# Generated by Django 5.1 on 2026-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_jenis_pengajuan_client_join_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Kredit Rekening Koran (PRK)'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL')], max_length=50),
        ),
    ]
