# Generated by Django 5.1 on 2026-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_jenis_pinjaman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='jenis_sertifikat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='restruktur',
        ),
        migrations.AlterField(
            model_name='client',
            name='jaminan',
            field=models.CharField(choices=[('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil'), ('SK_PNS', 'SK Pegawai Negeri')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Kredit Rekening Koran (PRK)'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)')], max_length=50),
        ),
    ]
