# Generated by Django 5.1 on 2026-04-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_jenis_sertifikat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bidang_usaha',
        ),
        migrations.RemoveField(
            model_name='client',
            name='jenis_pengajuan',
        ),
    ]
