# Generated by Django 5.1 on 2026-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_bidang_usaha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jumlah_pinjaman',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='pekerjaan',
            field=models.CharField(choices=[('KARYAWAN', 'Karyawan'), ('WIRASWASTA', 'Wiraswasta'), ('PROFESIONAL', 'Profesional'), ('ASN', 'PNS / ASN / Pemerintah'), ('TNI_POLRI', 'TNI / POLRI'), ('LAWYER', 'Lawyer'), ('BADAN_USAHA', 'Badan Usaha / Perusahaan / Yayasan')], max_length=50),
        ),
    ]
