# Generated by Django 5.1 on 2026-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_jumlah_pinjaman_alter_client_pekerjaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jumlah_pinjaman',
            field=models.IntegerField(),
        ),
    ]
