# Generated by Django 5.1 on 2026-04-12 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clienthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthistory',
            name='data',
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='jumlah_pinjaman',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='nama',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='tenor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='umur',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
