# Generated by Django 5.1 on 2026-04-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_clienthistory_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sumber_penghasilan',
            field=models.CharField(choices=[('HASIL_USAHA_TERCERMIN', 'Hasil Usaha Tercermin'), ('HASIL_USAHA_TIDAK_TERCERMIN', 'Hasil Usaha Tidak Tercermin'), ('GAJI_TRANSFER', 'Gaji Transfer'), ('GAJI_TUNAI', 'Gaji Tunai'), ('CAMPURAN', 'Campuran')], max_length=50),
        ),
    ]
