# Generated by Django 5.1 on 2026-04-15 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_client_sumber_penghasilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lama_usaha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nama_perusahaan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tipe_client',
            field=models.CharField(choices=[('PERORANGAN', 'Perorangan'), ('PERUSAHAAN', 'Perusahaan')], default='PERORANGAN', max_length=20),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='tipe_client',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('KARYAWAN', 'Karyawan'), ('WIRASWASTA', 'Wiraswasta'), ('PROFESIONAL', 'Profesional'), ('ASN', 'PNS / ASN / Pemerintah'), ('TNI_POLRI', 'TNI / POLRI'), ('LAWYER', 'Lawyer'), ('BADAN_USAHA', 'Badan Usaha / Perusahaan / Yayasan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_pekerjaan',
            field=models.CharField(blank=True, choices=[('TETAP', 'Tetap'), ('KONTRAK', 'Kontrak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
