# Generated by Django 5.1 on 2026-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_bidang_usaha_client_lama_usaha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jenis_sertifikat',
            field=models.CharField(blank=True, choices=[('SHM', 'SHM'), ('HGB', 'HGB'), ('SHRS', 'SHRS'), ('AJB', 'AJB'), ('GIRIK', 'Girik')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bidang_usaha',
            field=models.CharField(blank=True, choices=[('PERTANIAN', 'Pertanian, Kehutanan dan Perikanan'), ('PERTAMBANGAN', 'Pertambangan dan Penggalian'), ('INDUSTRI', 'Industri Pengolahan'), ('LISTRIK_GAS', 'Pengadaan Listrik, Gas, Uap/Air Panas dan Udara Dingin'), ('PENGELOLAAN_AIR', 'Pengelolaan Air, Limbah, Sampah, dan Remediasi'), ('KONSTRUKSI', 'Konstruksi'), ('PERDAGANGAN', 'Perdagangan Besar dan Eceran; Reparasi Mobil & Motor'), ('AKOMODASI', 'Akomodasi dan Makan Minum'), ('INFORMASI', 'Informasi dan Komunikasi'), ('KEUANGAN', 'Aktivitas Keuangan dan Asuransi'), ('REALESTAT', 'Real Estat'), ('PROFESIONAL', 'Aktivitas Profesional, Ilmiah dan Teknis'), ('SEWA', 'Aktivitas Penyewaan & Penunjang Usaha'), ('PEMERINTAHAN', 'Administrasi Pemerintahan, Pertahanan & Jaminan Sosial'), ('PENDIDIKAN', 'Pendidikan'), ('KESEHATAN', 'Kesehatan dan Aktivitas Sosial'), ('HIBURAN', 'Kesenian, Hiburan dan Rekreasi'), ('JASA_LAIN', 'Aktivitas Jasa Lainnya'), ('RUMAH_TANGGA', 'Aktivitas Rumah Tangga'), ('INTERNASIONAL', 'Badan Internasional & Ekstra Internasional')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Modal Kerja'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen (KPA)'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('KTA', 'Kredit Tanpa Agunan (KTA)'), ('KTA_ONLINE', 'KTA Online Seller'), ('DEPOSITO', 'Deposito Berjangka')], max_length=50),
        ),
    ]
