# Generated by Django 5.1 on 2026-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_jenis_sertifikat_alter_client_bidang_usaha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthistory',
            name='bentuk_perusahaan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='jaminan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='jenis_pinjaman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='join_income',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='status_pekerjaan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='status_slik',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='sumber_penghasilan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
