# Generated by Django 5.1 on 2026-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clienthistory_bentuk_perusahaan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthistory',
            name='bidang_usaha',
        ),
        migrations.RemoveField(
            model_name='clienthistory',
            name='results',
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='bentuk_perusahaan',
            field=models.CharField(blank=True, choices=[('PERORANGAN', 'Perorangan'), ('PT', 'PT'), ('CV', 'CV'), ('YAYASAN', 'Yayasan'), ('PEMERINTAH', 'Pemerintah')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jaminan',
            field=models.CharField(blank=True, choices=[('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil'), ('SK_PNS', 'SK Pegawai Negeri')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jenis_pinjaman',
            field=models.CharField(blank=True, choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Modal Kerja'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen (KPA)'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('KTA', 'Kredit Tanpa Agunan (KTA)'), ('KTA_ONLINE', 'KTA Online Seller'), ('DEPOSITO', 'Deposito Berjangka')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='join_income',
            field=models.CharField(blank=True, choices=[('TIDAK', 'Tidak'), ('PASANGAN', 'Pasangan'), ('ORANG_TUA', 'Orang Tua')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('KARYAWAN', 'Karyawan'), ('WIRASWASTA', 'Wiraswasta'), ('PROFESIONAL', 'Profesional'), ('ASN', 'PNS / ASN / Pemerintah'), ('TNI_POLRI', 'TNI / POLRI'), ('LAWYER', 'Lawyer'), ('BADAN_USAHA', 'Badan Usaha / Perusahaan / Yayasan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='status_pekerjaan',
            field=models.CharField(blank=True, choices=[('TETAP', 'Tetap'), ('KONTRAK', 'Kontrak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='status_slik',
            field=models.CharField(blank=True, choices=[('KOL1', 'Kol 1'), ('KOL2', 'Kol 2'), ('KOL3', 'Kol 3'), ('KOL5', 'Kol 5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='sumber_penghasilan',
            field=models.CharField(blank=True, choices=[('HASIL_USAHA_TERCERMIN', 'Hasil Usaha Tercermin'), ('HASIL_USAHA_TIDAK_TERCERMIN', 'Hasil Usaha Tidak Tercermin'), ('GAJI_TRANSFER', 'Gaji Transfer'), ('GAJI_TUNAI', 'Gaji Tunai'), ('CAMPURAN', 'Campuran')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='tipe_client',
            field=models.CharField(blank=True, choices=[('PERORANGAN', 'Perorangan'), ('PERUSAHAAN', 'Perusahaan')], max_length=20, null=True),
        ),
    ]
