# Generated by Django 5.1 on 2026-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_jenis_pinjaman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jaminan',
            field=models.CharField(choices=[('TANPA_JAMINAN', '-'), ('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil'), ('SK_PNS', 'SK Pegawai Negeri'), ('OBJEK_PEMBIAYAAN', 'Objek Pembiayaan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jaminan',
            field=models.CharField(blank=True, choices=[('TANPA_JAMINAN', '-'), ('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil'), ('SK_PNS', 'SK Pegawai Negeri'), ('OBJEK_PEMBIAYAAN', 'Objek Pembiayaan')], max_length=50, null=True),
        ),
    ]
