# Generated by Django 5.1 on 2026-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_jenis_pinjaman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bentuk_perusahaan',
            field=models.CharField(blank=True, choices=[('PERORANGAN', 'Perorangan'), ('PT', 'PT'), ('CV', 'CV'), ('YAYASAN', 'Yayasan'), ('PEMERINTAH', 'Pemerintah'), ('RUMAH_SAKIT', 'Rumah Sakit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='bentuk_perusahaan',
            field=models.CharField(blank=True, choices=[('PERORANGAN', 'Perorangan'), ('PT', 'PT'), ('CV', 'CV'), ('YAYASAN', 'Yayasan'), ('PEMERINTAH', 'Pemerintah'), ('RUMAH_SAKIT', 'Rumah Sakit')], max_length=50, null=True),
        ),
    ]
