# Generated by Django 5.1 on 2026-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_client_bentuk_perusahaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Modal Kerja'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('DANA_TALANGAN_GAJI', 'Dana Talangan Gaji (Payroll Financing)'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen (KPA)'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('KTA', 'Kredit Tanpa Agunan (KTA)'), ('KTA_ONLINE', 'KTA Online Seller'), ('DEPOSITO', 'Deposito Berjangka'), ('ANGSURAN', 'Angsuran')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jenis_pinjaman',
            field=models.CharField(blank=True, choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Modal Kerja'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('DANA_TALANGAN_GAJI', 'Dana Talangan Gaji (Payroll Financing)'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen (KPA)'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('KTA', 'Kredit Tanpa Agunan (KTA)'), ('KTA_ONLINE', 'KTA Online Seller'), ('DEPOSITO', 'Deposito Berjangka'), ('ANGSURAN', 'Angsuran')], max_length=50, null=True),
        ),
    ]
