# Generated by Django 5.1 on 2026-05-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_alter_client_jenis_pinjaman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jaminan',
            field=models.CharField(choices=[('TANPA_JAMINAN', '-'), ('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil'), ('SK_PNS', 'SK Pegawai Negeri'), ('OBJEK_PEMBIAYAAN', 'Objek Pembiayaan'), ('SIP', 'SIP (Surat Izin Praktek)'), ('BERLIAN', 'Berlian'), ('EMAS', 'Emas'), ('ARLOJI_MEWAH', 'Arloji Mewah'), ('MOGE', 'Motor Gede'), ('MATA_UANG_ASING', 'Mata Uang Asing (SGD, USD, EUR)'), ('KARTU_POKEMON', 'Kartu Pokemon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='jenis_pinjaman',
            field=models.CharField(choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Modal Kerja'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('DANA_TALANGAN_GAJI', 'Dana Talangan Gaji (Payroll Financing)'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen (KPA)'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('KTA', 'Kredit Tanpa Agunan (KTA)'), ('KTA_ONLINE', 'KTA Online Seller'), ('DEPOSITO', 'Deposito Berjangka'), ('ANGSURAN', 'Angsuran'), ('GADAI', 'Gadai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_slik',
            field=models.CharField(choices=[('-', '-'), ('KOL1', 'Kol 1'), ('KOL2', 'Kol 2'), ('KOL3', 'Kol 3'), ('KOL5', 'Kol 5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jaminan',
            field=models.CharField(blank=True, choices=[('TANPA_JAMINAN', '-'), ('RUMAH', 'Rumah'), ('APARTEMEN', 'Apartemen'), ('RUKO', 'Ruko / Rukan'), ('TANAH', 'Tanah'), ('GUDANG', 'Gudang'), ('KIOS', 'Kios'), ('KOST', 'Kost'), ('VILA', 'Vila'), ('INVOICE', 'Invoice'), ('SPK', 'SPK / PO'), ('BPKB', 'BPKB Mobil'), ('SK_PNS', 'SK Pegawai Negeri'), ('OBJEK_PEMBIAYAAN', 'Objek Pembiayaan'), ('SIP', 'SIP (Surat Izin Praktek)'), ('BERLIAN', 'Berlian'), ('EMAS', 'Emas'), ('ARLOJI_MEWAH', 'Arloji Mewah'), ('MOGE', 'Motor Gede'), ('MATA_UANG_ASING', 'Mata Uang Asing (SGD, USD, EUR)'), ('KARTU_POKEMON', 'Kartu Pokemon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='jenis_pinjaman',
            field=models.CharField(blank=True, choices=[('KPR_PRIMARY', 'KPR Primary'), ('KPR_SECONDARY', 'KPR Secondary'), ('MULTIGUNA', 'Multiguna / Refinancing'), ('TAKE_OVER_MURNI', 'Take Over Murni'), ('TAKE_OVER_JUAL_BELI', 'Take Over Jual Beli'), ('TAKE_OVER_SME', 'Take Over dari SME (Fasilitas & Jaminan atas nama perorangan)'), ('INVESTASI', 'Kredit Investasi'), ('PRK', 'Modal Kerja'), ('INVOICE', 'Kredit Invoice Financing'), ('SPK', 'Kredit PO / SPK Financing'), ('BPKB', 'BPKB Mobil'), ('MICRO', 'Micro'), ('KOST', 'Pembiayaan Kost-kostan'), ('BRIDGING_OL', 'Bridging OL'), ('DANA_TALANGAN_BPJS', 'Dana Talangan BPJS'), ('DANA_TALANGAN_GAJI', 'Dana Talangan Gaji (Payroll Financing)'), ('ITSI', 'Investasi Terikat Syariah Indonesia (ITSI)'), ('SEWA_PROPERTY', 'Sewa Property'), ('RENOVASI', 'Renovasi Properti'), ('KPA', 'Kredit Pemilikan Apartemen (KPA)'), ('LOGAM_MULIA', 'Cicil Logam Mulia'), ('KTA', 'Kredit Tanpa Agunan (KTA)'), ('KTA_ONLINE', 'KTA Online Seller'), ('DEPOSITO', 'Deposito Berjangka'), ('ANGSURAN', 'Angsuran'), ('GADAI', 'Gadai')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='status_slik',
            field=models.CharField(blank=True, choices=[('-', '-'), ('KOL1', 'Kol 1'), ('KOL2', 'Kol 2'), ('KOL3', 'Kol 3'), ('KOL5', 'Kol 5')], max_length=10, null=True),
        ),
    ]
